name:                stm-ixset
version:             0.1.0.0
github:              "lolepezy/stm-ixset"
license:             BSD3
author:              "Author name here"
maintainer:          "misha.puzanov@gmail.com"
copyright:           "2018 Misha Puzanov"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/lolepezy/stm-ixset#readme>

dependencies:
- base >= 4.7 && < 5
- async
- containers
- hashable
- stm
- stm-containers

library:
  source-dirs: src

tests:
  stm-ixset-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - stm-ixset
    - QuickCheck
    - tasty
    - tasty-hunit
    - tasty-quickcheck
